### PR TITLE
fix chunk border rendering

### LINKED ISSUE #2125: subchunk outline
### What happened?

iris mod affects the color of the subchunk outline
make it invisible

### Screenshots

image
image

### Log output

_No response_

### Minecraft Version

1.20.1

### Iris Version

iris-mc1.20.1-1.6.8

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce RTX 2070 Max-Q

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Plastoid501**
fix https://github.com/IrisShaders/Iris/issues/2125. I didn't know where to put the file, so I put it under `net/irisshaders/iris/mixin`. I would appreciate it if you could move it to an appropriate location.

### CODE REVIEW

**Comment by IMS212** [comment]
Would it be possible to add comments explaining what these do?

**Comment by Plastoid501** [comment]
Normally, overlapping lines make the line drawn later visible. In this case, however, the first line was visible. So I deleted the unwanted line drawn at the beginning of the overlapping lines. The `isCameraChunk` and `isSubChunk` methods make the red vertical line and the blue SubChunkBorder line correctly visible.

**Comment by Plastoid501** [comment]
The process of the @.Slice part is `isCameraChunk`, which draws red vertical lines in the corners of a 3x3 chunk centered on the chunk with the camera, and `isSubChunk`, which draws yellow lines every 2 blocks and dark cyan lines every 8 blocks. So `isCameraChunk` cancels the process of drawing the corners of the chunk with the camera, and `isSubChunk` cancels the process of drawing the borders of the subchunks every 16 blocks.

**Comment by IMS212** [comment]
Can you rebase this onto multiloader-new?

**Comment by Plastoid501** [comment]
Sorry, I must have made a mistake with the rebase. I don't know how to fix it, so should I change the branch to multiloader-new and Pull Request it again? I am so sorry.

**Comment by fayer3** [comment]
you need to change the target branch in the PR
click on edit in the top right, and change the base branch

**Comment by Plastoid501** [comment]
Is this correct? Sorry for the disturbance.

**Comment by fayer3** [comment]
looks fine to me now

**Comment by IMS212** [comment]
Thanks!

**Pull request merged**
