### PR TITLE
Update README.md with a fix for some shaders failing to compile on Linux.

### PR DESCRIPTION
**Pull request by satyrnsstuff**
Fixed SEUS Renewed for me.

### CODE REVIEW

**Comment by coderbot16** [comment]
I'm curious how this helps for SEUS Renewed, since SEUS Renewed doesn't appear to contain GLSL #extension directives which these flags affect?

**Comment by satyrnsstuff** [comment]
`allow_glsl_extension_directive_midshader=true` might not entirely necessary, although I've heard it fixes some errors with broken shaders. But, SEUS Renewed completely fails to compile without `force_glsl_extensions_warn=true` for some reason on Linux with an AMD GPU. As to why this is the case, I'm not entirely sure. It also is require to run SEUS Renewed in the same environment, with Optifine.

**Comment by satyrnsstuff** [comment]
Considering the fact that this is both for Iris, and OptiFine, I will be closing this PR.

**Comment by AlsoNiko** [comment]
I have had another user report this actually fixing SEUS renewed for them (but breaking complementary)
`force_glsl_extensions_warn=true`
logs for before and after are included

SEUS applied first, has tons of visual bugs. Comp is second, works fine 
[latest (32).log](https://github.com/IrisShaders/Iris/files/6836806/latest.32.log) (Seus first, than comp)

Comp first, fall back to vanilla. SEUS after, works perfectly 
[latest (33).log](https://github.com/IrisShaders/Iris/files/6836809/latest.33.log)

**Comment by coderbot16** [comment]
Thanks for this PR, but it is no longer needed. Iris now moves `#extension` directives around itself to fix this issue, now these shaders should work out of the box without additional configuration with the latest commits to Iris.

**Pull request closed without merging**
