### PR TITLE
Fix overlay texture unit, fixes hit flash without shaders

### PR DESCRIPTION
**Pull request by IMS212**
I couldn't find any reason this was set to 6, am I missing something?

### CODE REVIEW

**Comment by coderbot16** [comment]
This was previously set to 6 to avoid a potential clash with the old sampler system, but it's no longer an issue. I'm curious why setting this to 2 instead of 6 fixes issues, however, since vanilla sets the overlay texture unit to 1, so it doesn't even match vanilla. Odd.

**Comment by IMS212** [comment]
Not sure either, however it seems to work without any noticeable issues with shaders on or off.

**Comment by IMS212** [comment]
This should be ready for merge.

**Comment by IMS212** [comment]
Marking this as high priority, as this breaks vanilla behavior.

**Comment by IMS212** [comment]
Merging, as I have been testing this for a few hours with no noticable issues.

**Pull request merged**
