### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by omahs**
Fix typos

### CODE REVIEW

**Comment by IMS212** [comment]
trying to farm I see

**Comment by omahs** [comment]
@IMS212 farm what exactly? It seems that you don't always respond like that to relatively minor PR, is it because of hacktoberfest?

**Comment by IMS212** [comment]
yes

**Comment by omahs** [comment]
@IMS212 Ok, good to know. I often fix docs, hope not to have too many reactions like this. Wishing you a nice day

**Pull request closed without merging**
