### PR TITLE
Add fallback path in case the atlassize didn't get stored

### PR DESCRIPTION
**Pull request by Kroppeb**
I tested this be commenting out the original code, and it seems to not crash with the fix. I couldn't really see a difference with noisy textures on or off so idk if it actually works as intended.

### CODE REVIEW

**Review by coderbot16 — CHANGES_REQUESTED** [review]
The issue I see with this code is that it potentially trashes the current texture binding. There should be a way to restore the previous binding once the code is done.

**Comment by Kroppeb** [comment]
> The issue I see with this code is that it potentially trashes the current texture binding. There should be a way to restore the previous binding once the code is done.

Oh, I thought `RenderSystem.bindTexture(glId);` would be all that is needed.

**Comment by coderbot16** [comment]
Changing the texture binding with bindTexture and not restoring it is dangerous when this code could be called at pretty much any time - it would work fine most of the time but potentially cause weird intermittent issues some of the time. Restoring the binding at the end would avoid those potential issues.

**Review by coderbot16 — COMMENTED** [review]
I'll merge this and fix the texture binding issue myself. Thanks for the dashloader compatibility fix!

**Pull request merged**
