### PR TITLE
Update to Loom 0.9, yarn build 32, and link in gradle.properties

### PR DESCRIPTION
**Pull request by IMS212**
This has no changes on it's own, but is good for futureproofing.

### CODE REVIEW

**Comment by IMS212** [comment]
Will merge soon if there are no complaints, as this is a small change.

**Comment by coderbot16** [comment]
Mappings updates can be dangerous in the context of Yarn's name swaps. Have you audited the mappings changes for any issues like that?

**Comment by IMS212** [comment]
I haven’t audited it, however I have tested it and it runs fine in development.

**Comment by IMS212** [comment]
I've just tested it in production, and it runs fine.

**Review by coderbot16 — CHANGES_REQUESTED** [review]
Gradle & loom updates are fine, but I think we shouldn't update Yarn. Instead, we should focus on moving to mojmap. Also, is there any reason we can't use Loom 0.9 / modern Gradle on trunk?

**Comment by IMS212** [comment]
Loom 0.9 forces the use of Java 16. The mojang mapping PR is almost complete, just needs a few finishing touches.

**Comment by DragonEggBedrockBreaking** [comment]
As IMS said, Loom 0.9 forces use of Java 16, but modern gradle should be fine - afaik Loom 0.6 supports Gradle 7.x

**Comment by BeansBeefBroccoli** [comment]
Updating yarn should no longer be needed now as coderbot and IMS have converted to Iris mojmap.

**Pull request closed without merging**
