### PR TITLE
Update to Fabric Loader 0.12, and use Mixin 0.8.4

### PR DESCRIPTION
**Pull request by IMS212**
This will force 0.12 as the minimum loader, so this should be on hold until 0.12 is considered stable enough for use.

### CODE REVIEW

**Comment by BeansBeefBroccoli** [comment]
What did you change in `MixinChunkRebuildTask.java`?

**Comment by IMS212** [comment]
Some Mixin 0.8.4 changes had to be made.

**Comment by BeansBeefBroccoli** [comment]
K

**Review by coderbot16 — CHANGES_REQUESTED** [review]
One of the primary reasons for maintaining 1.16.5 support aside from debugging & potentially better performance is modpack support. Have you checked whether relevant 1.16.5 modpacks are using Fabric Loader 0.12? If not, it might make sense to retain 0.11 compatibility even if we use 0.12 in development.

**Comment by IMS212** [comment]
Just realized this will allow us to get rid of 2 overwrites in MixinBufferVertexConsumer as well due to 0.12.3+ supporting injections into interfaces, so I think we should go ahead. Most 1.16.5 modpacks use 0.12.3+ now.

**Comment by IMS212** [comment]
Will be making a new PR to take advantage of this.

**Pull request closed without merging**
