### PR TITLE
Comment out "test", which now means Iris can be built.

### PR DESCRIPTION
**Pull request by BeansBeefBroccoli**
/*
test {
	// Use JUnit 5 Platform for tests
	useJUnitPlatform()
}
*/

### CODE REVIEW

**Comment by IMS212** [comment]
This isn't a proper fix, a proper fix would be actually fixing what makes the tests fail.

**Comment by BeansBeefBroccoli** [comment]
Ok, I just wanted to do this because the feature wasn't fixed in the next, like, 3 commits, and I wanted to fix this for others until the feature gets properly introduced.

**Comment by BeansBeefBroccoli** [comment]
I have no idea how to code graphics with MC, if I did, I would try to actually help with the feature.

**Comment by IMS212** [comment]
Closed in favor of a new PR I'm making which correctly fixes this

**Comment by BeansBeefBroccoli** [comment]
Ok, thank you! :+1:

**Pull request closed without merging**
