### PR TITLE
Add Pirate Speak translation.

### PR DESCRIPTION
**Pull request by NoComment1105**
Please Cherry pick out the first 4 commits in here, they're from an unmerged PR i have on iris (#702). I couldn't get git to ignore them :P

### CODE REVIEW

**Review by IMS212 — APPROVED** [review]

**Comment by IMS212** [comment]
Closing and directly merging due to the issues with the git history.

**Comment by NoComment1105** [comment]
yeah git did have a massive stroke

**Comment by coderbot16** [comment]
If you want to have more than one open PR, you need to have more than one branch to use, you can't put everything on the same branch of your fork.

**Comment by NoComment1105** [comment]
It was actually on a seperate branch, i'm very confused on what happened

**Pull request closed without merging**
