### PR TITLE
Add the lightmap to the terrain shader

### PR DESCRIPTION
**Pull request by ColdIce1605**
fixed lighting 
 - terrain matches entities
 - terrain now has lighting
@coderbot16

### CODE REVIEW

**Comment by ColdIce1605** [comment]
thing to notice the lmcoord doesn't match the tex or to most devs texcoord this doesn't really affect anything but uniformity.

**Review by coderbot16 — CHANGES_REQUESTED** [review]
Looks good, thanks! But if texcoord is more standard then it would probably be good to use that instead.

Also, no need to mention me, I'm watching the repository so I get notifications for everything.

**Review by ColdIce1605 — COMMENTED** [review]
all changed

**Comment by ColdIce1605** [comment]
another thing is I changed what is assigned to texcoord to be more like lmcoord

**Review by coderbot16 — APPROVED** [review]
LGTM

**Pull request merged**
