### PR TITLE
cameraType Iris exclusive uniform

### PR DESCRIPTION
**Pull request by IMS212**
0 - first person/unknown
1 - third person back
2 - third person front

that's it

### CODE REVIEW

**Comment by coderbot16** [comment]
Is there any reason to distinguish between third person perspective types rather than this just being a boolean of whether or not the camera is in first person or not?

**Comment by IMS212** [comment]
Not really, I just didn’t see a reason *not to*

**Comment by coderbot16** [comment]
Well, there's mods like freelook that allow the user to move the third person camera around the player model (without rotating the player head/model), instead of having it just look forwards and backwards, and there wouldn't be a coherent way to express that with this approach.

**Comment by IMS212** [comment]
Finally fixed.

**Comment by coderbot16** [comment]
Couldn't we call this `firstPersonCamera` or something?

**Comment by IMS212** [comment]
Sure, I'll also make it a bool.

**Comment by IMS212** [comment]
Uniform is now firstPersonCamera boolean.

**Review by coderbot16 — APPROVED** [review]
Code looks good, thanks. This should be added to ShaderDoc as well.

**Pull request merged**
