### PR TITLE
Replace Sodium sky Mixin with custom one

### PR DESCRIPTION
**Pull request by IMS212**
Not ideal, but it should work.

### CODE REVIEW

**Review by Justsnoopy30 — APPROVED** [review]
Looks good, however it is liable to the bug in the release sodium version with it not respecting mod's custom mixin configs on first lunch. But we can't do much about that and it's not really that big of a deal.

**Comment by Justsnoopy30** [comment]
I've also tested this PR and it appears to work fine.

**Comment by tbejos** [comment]
> Looks good, however it is liable to the bug in the release sodium version with it not respecting mod's custom mixin configs on first lunch. But we can't do much about that and it's not really that big of a deal.

Should be fixed in next Sodium Release CaffeineMC/sodium-fabric#973

**Comment by Justsnoopy30** [comment]
Yep, it is, but that's not out yet so we still have to think about the currently released version.

**Comment by IMS212** [comment]
Fixes part of #983

**Comment by coderbot16** [comment]
We'll probably have to wait for the next Sodium release for 1.17 for this to actually work. Or at least, I hope Sodium will get a final 1.17 release.

**Review by coderbot16 — CHANGES_REQUESTED** [review]
We might want to be more clear that this is copied and modified from Sodium.

**Comment by IMS212** [comment]
Done

**Comment by coderbot16** [comment]
Seems like there's some merge conflicts, could you please resolve them?

**Comment by IMS212** [comment]
Done!

**Comment by coderbot16** [comment]
Thanks!

**Comment by cssmc** [comment]
cringe

**Comment by IMS212** [comment]
ok

**Comment by BeansBeefBroccoli** [comment]
@cssmc Why?

**Comment by coderbot16** [comment]
banned.

**Pull request merged**
