### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by Isuewo**
Updates the German translation to include translations for the debug strings

### CODE REVIEW

**Review by douira — APPROVED** [review]
lgtm

**Comment by IMS212** [comment]
you'll need to update to new commit

**Review by douira — APPROVED** [review]
Looks good

**Comment by Isuewo** [comment]
Please merge @IMS212 or leave it open if further changes are planned

**Comment by IMS212** [comment]
I do plan to add more translation strings for debug, so I'll keep this open for now.

**Comment by IMS212** [comment]
ok it's merge time

**Comment by Isuewo** [comment]
So no more debugging then?

**Comment by douira** [comment]
nope, not for now

**Pull request merged**
