### PR TITLE
Remove un-used code in issue config 

### PR DESCRIPTION
**Pull request by NoComment1105**
Tiny PR. Small typo in the issue config I noticed while reading it.

### CODE REVIEW

**Comment by IMS212** [comment]
Is this not intentionally enabled?

**Comment by NoComment1105** [comment]
It was enabled before, however it does completely remove the new issue opening ability which coderbot likes, so I might remove the option entirely, depending on what coder says

**Comment by coderbot16** [comment]
Being able to open blank issues is nice for developers to use the issue tracker as a more formal "TODO" list. I don't think users opening blank issues has been a problem. So we should probably just leave them enabled. Worst case, if a user opens a blank issue, we can always ask them to reopen using the template if they don't provide enough info.

**Comment by NoComment1105** [comment]
Alright, I'm gonna reopen this with the line removed

**Comment by NoComment1105** [comment]
Sorted

**Review by coderbot16 — APPROVED** [review]
Thanks!

**Pull request merged**
