### PR TITLE
gbuffers_entities_trans

### PR DESCRIPTION
**Pull request by IMS212**
people have been asking for this for literally 5 years and I added it in 20 minutes

gg optifine

### CODE REVIEW

**Comment by coderbot16** [comment]
I don't think this is robust enough... This will actually need the blending state to be checked instead of hardcoding render type names.

**Comment by IMS212** [comment]
Sounds good, will do. Is the program usage itself OK?

**Comment by coderbot16** [comment]
The setup looks fine but I think this is something that should be checking the blend state from glstatemanager instead of involving itself with render types at all.

**Comment by IMS212** [comment]
hm, ok. That works, I guess.

**Comment by IMS212** [comment]
Fixed.

**Comment by IMS212** [comment]
Will merge soon. This optionally depends on feature flags existing.

**Pull request merged**
