### PR TITLE
Arrival of the Tactical Nuke

### PR DESCRIPTION
**Pull request by IMS212**
With this PR, all versions below 1.20.1 will no longer be supported.

### CODE REVIEW

**Comment by alex89912** [comment]
Why deprecating the older versions?

**Comment by IMS212** [comment]
they all suck

**Comment by IMS212** [comment]
maybe

**Comment by alex89912** [comment]
Uuh how, DH incompatibility warning?

**Comment by Lolothepro** [comment]
> Does this PR fix a lot of bugs in Iris?

No

**Comment by IMS212** [comment]
Iris 1.7.

**Comment by IMS212** [comment]
minecraft 2

**Comment by IMS212** [comment]
we ball

**Comment by pikesthefish** [comment]
As of now, 1.19 is not anymore supported?

**Comment by IMS212** [comment]
no more 1.19

**Pull request merged**
