### PR TITLE
Make GH Actions upload artifacts.

### LINKED ISSUE #1249: Upload artifacts when GH Actions are done.
**Is your feature request related to a problem? Please describe.**
I would like that GH Actions in this repository would upload artifacts.

**Describe the solution you'd like**
Use the [Upload a Build Artifact](https://github.com/marketplace/actions/upload-a-build-artifact) to upload artifacts to GH Actions.

**Describe alternatives you've considered**
None.

**Additional context**
I could make a PR for this.

Related PR: #1250

### PR DESCRIPTION
**Pull request by pjalsGit**
This will make GH Actions upload artifacts upon build completion. (might or might not work first try)

Fixes #1249

### CODE REVIEW

**Comment by NoComment1105** [comment]
See #1249

**Comment by IMS212** [comment]
If you want to use purposely unreleased builds, you are expected to take responsibility for compiling and debugging it.

**Comment by BeansBeefBroccoli** [comment]
I understand but it's very inconvenient for a slow machine.

**Comment by coderbot16** [comment]
I added a document clarifying why this is the case, and providing hints at the steps for users to get their own dev builds: https://github.com/IrisShaders/Iris/blob/trunk/docs/usage/development-builds.md

**Pull request closed without merging**
