### PR TITLE
Add support for the hand depth macro

### PR DESCRIPTION
**Pull request by maximumpower55**

### CODE REVIEW

**Comment by coderbot16** [comment]
Should we make this a constant in a single place instead of hardcoding it in two places?

**Comment by maximumpower55** [comment]
Sure would defining it in the main hand rendering class work?

**Comment by coderbot16** [comment]
That sounds fine for now

**Comment by maximumpower55** [comment]
> That sounds fine for now

Added.

**Review by coderbot16 — APPROVED** [review]
Thanks!

**Pull request merged**
