### PR TITLE
add working fogStart and fogEnd

### LINKED ISSUE #681: there is no fogStart and fogEnd
### What happened?

A bug happened!

### Screenshots

_No response_

### Relevant log output

_No response_

### Iris and Minecraft Version

iris 1.1.1 and 1.1.2-pre 1.17.1

### Are you running Sodium along with Iris?

No

### Operating System

ubuntu 20.04

### What is your GPU?

absolutely not

### Java Version

java -1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TehcJS**
fixes #681

### CODE REVIEW

**Comment by coderbot16** [comment]
Why not use `gl_Fog.start` and `gl_Fog.end` ?

**Comment by TehcJS** [comment]
glsl 1.5 removed those

**Comment by coderbot16** [comment]
It's still valid to use them with Iris, since it patches from the compatibility profile to the core profile. But I understand that some shader authors really don't want to work with compatibility profile features.

I'd rather see what OptiFine is doing with regards to exposing vanilla uniforms like this to shaders instead of implementing our own incompatible approach.

**Comment by TehcJS** [comment]
it is what optifine is doing though? it's in the optifine docs

**Comment by coderbot16** [comment]
There are no mentions of fogStart and fogEnd in the [optifine docs](https://github.com/sp614x/optifine/blob/eeb28cf187ff8d9beb3fb5442a7631d0029fd34e/OptiFineDoc/doc/shaders.txt).

**Comment by TehcJS** [comment]
is there any alternative to this without using the compatibility profile?

**Comment by IMS212** [comment]
According to some info in shaderlabs, fogStart and fogEnd are valid.

**Comment by TehcJS** [comment]
Also, I tested it in optifine; it's valid to use `fogStart` and `fogEnd`.

**Comment by TehcJS** [comment]
image

**Comment by coderbot16** [comment]
`FogStart` and `FogEnd` aren't the same as `fogStart` and `fogEnd`, uniform names are case sensitive.

**Comment by TehcJS** [comment]
I can confirm `fogStart` and `fogEnd` work in the latest Optifine version 1.17.1

**Comment by ColdIce1605** [comment]
Oh yeah I do remember that we should probably allow vanilla uniforms as that kinda how OF patches shaders.

**Comment by ColdIce1605** [comment]
@TehcJS (not sure if you're watching)
You could change this PR to be more general and allow all built-in vanilla uniforms too of course along with the OF names(old uniforms)

**Comment by TehcJS** [comment]
ok i will do that tmr or something

**Pull request closed without merging**
