### PR TITLE
Modernize ShadowRenderer for 1.17

### PR DESCRIPTION
**Pull request by IMS212**
Take 2, remade with both issues fixed!

### CODE REVIEW

**Comment by coderbot16** [comment]
I pushed a rework to trunk that should address the blend mode stuff more cleanly on all versions.

**Comment by coderbot16** [comment]
This conflicts due to the previously-mentioned blend mode override changes.

**Comment by IMS212** [comment]
Fixed

**Review by coderbot16 — APPROVED** [review]
Thanks! This looks much nicer.

**Pull request merged**
