### PR TITLE
Added the abillity to see the currently loaded shader in the options menu

### PR DESCRIPTION
**Pull request by hYdos**
Yes

### CODE REVIEW

**Comment by coderbot16** [comment]
I don't think that Iris should clutter up the options screen like this - maybe the f3 screen is more appropriate?

**Comment by hYdos** [comment]
> 
> 
> I don't think that Iris should clutter up the options screen like this - maybe the f3 screen is more appropriate?

ok. ill move that code into the f3 menu :tiny_potato:

**Comment by ColdIce1605** [comment]
kek

**Comment by IMS212** [comment]
made #33 to succeed this

**Comment by coderbot16** [comment]
Since #33 was merged, I will close this for now.

However, having a proper Iris configuration gui (maybe accessed through the options menu?) would be pretty great, if you're interested in that.

**Pull request closed without merging**
