### PR TITLE
Code conversion to Mojang mappings

### PR DESCRIPTION
**Pull request by IMS212**
This is an overall solution to #679, although not everything has been renamed yet, and this will break practically all pending PR's.

### CODE REVIEW

**Comment by IMS212** [comment]
This should be mostly done, will work on resolving the conflicts today.

**Comment by IMS212** [comment]
Actually, there's one more issue left to resolve, the redirect in MixinOption. It does not like the current system for some reason.

**Comment by IMS212** [comment]
With some help from people over in the Mixin discord, the last major issue has been fixed!

**Comment by IMS212** [comment]
OK, I _actually_ fixed the issue this time, and this should be ready for review.

**Comment by IMS212** [comment]
Should be ready for review, manually merged all the 1.1.2 commits and fixed a major shadow culling bug.

**Comment by coderbot16** [comment]
Thanks! I touched up a bunch of the code myself but this is good otherwise.

**Pull request merged**
