### PR TITLE
mainUnitSize uniform, atlasSize for non-atlases

### PR DESCRIPTION
**Pull request by IMS212**

### CODE REVIEW

**Comment by coderbot16** [comment]
I would have no idea what `mainUnitSize` meant without looking at the code. Maybe gtextureSize or something like that instead?

**Comment by IMS212** [comment]
Done.

**Comment by coderbot16** [comment]
Why not just make this unconditionally available? I don't think it's necessary to make it only available for non-atlases.

**Comment by IMS212** [comment]
I guess so, will do.

**Comment by IMS212** [comment]
done

**Comment by IMS212** [comment]
Will merge soon if there are no complaints.

**Review by coderbot16 — APPROVED** [review]
Looks good!

**Pull request merged**
