### PR TITLE
Updated readme file

### PR DESCRIPTION
**Pull request by Ram-tyagi**
Added contributors in the readme file

### CODE REVIEW

**Comment by Ram-tyagi** [comment]
yes it is

**Comment by douira** [comment]
Can you elaborate?

**Comment by Ram-tyagi** [comment]
no need to go on the other page we can simply see them below in the readme file.


Screenshot 2023-10-25 210738

**Comment by IMS212** [comment]
This seems objectively worse.

You can't click on the contributors, it's not listed who they are, and it takes up a lot of space.

**Pull request closed without merging**
