### PR TITLE
Add ModMenu integration

### PR DESCRIPTION
**Pull request by Grayray75**
With this the Iris config GUI can be opened via the ModMenu.

### CODE REVIEW

**Review by DragonEggBedrockBreaking — APPROVED** [review]

**Comment by soup6020** [comment]
Confirming this works

**Comment by FoundationGames** [comment]
Does this pull request add a special config screen for Iris or does it simply link the shader pack screen?
There are plans to make a proper, dedicated and separate configuration screen specifically for any of Iris's additional mod settings (as well as a link to the shader pack screen) and have that be accessible through mod menu, rather than directly linking the pack screen to mod menu.
If this is meant as a temporary solution until then, that would be ok by me.

**Comment by soup6020** [comment]
It adds a config button under the mod's section in ModMenu that leads to the shader pack configuration screen

**Comment by soup6020** [comment]
image

**Comment by soup6020** [comment]
image
it takes you here

**Comment by coderbot16** [comment]
Thanks for the PR! I used your code as a basis, but I found a way to add integration without depending on the TerraformersMC maven repository.

**Pull request closed without merging**
