### PR TITLE
Update bulid*.yml

### PR DESCRIPTION
**Pull request by LY-Xiang**
actions/* v2->v4
Kir-Antipov/mc-publish v3.2->v3.3

### CODE REVIEW

**Comment by IMS212** [comment]
Um... this doesn't actually build.

**Review by Kichura — COMMENTED** [review]
The checkout step has no "name" statement, meaning it has no friendly name.

**Comment by LY-Xiang** [comment]
L13 
- name: Checkout sources

**Review by Kichura — APPROVED** [review]
Despite `check-latest: true` being excluded below `java-version: 17` for auto-updating reasons - lgtm.

**Pull request closed without merging**
