### PR TITLE
Add batched rendering implementation version 2.1

### PR DESCRIPTION
**Pull request by IMS212**

### CODE REVIEW

**Comment by IMS212** [comment]
I've disabled the code for the debug information and the sneak to disable, as those were never meant to be in production.

**Comment by IMS212** [comment]
Particles seem to have disappeared, looking into it now.

**Comment by IMS212** [comment]
Fixed.

**Comment by coderbot16** [comment]
Thanks for the PR, but I ended up doing this myself to make sure I didn't miss anything (like implementing WrappingVertexConsumerProvider) and because I wanted a different package layout:

https://github.com/IrisShaders/Iris/compare/e87aacad9584...3fe8f9194de3

**Pull request closed without merging**
