### PR TITLE
Simplified Chinese Translations

### PR DESCRIPTION
**Pull request by klkq**
Translation for Simplified Chinese.
The translation for _shader pack_ is kept identical to that in Optifine.

### CODE REVIEW

**Review by DragonEggBedrockBreaking — CHANGES_REQUESTED** [review]
You probably updated the build CI on the wrong branch?

**Comment by klkq** [comment]
Sorry. Is it OK now?

**Comment by klkq** [comment]
> You probably updated the build CI on the wrong branch?

Sorry. Is it OK now?

**Comment by klkq** [comment]
Please delete this PR. Maybe I shouldn't have used force-push.

**Pull request closed without merging**
