### PR TITLE
Update README.md according to the advances made

### PR DESCRIPTION
**Pull request by Pepe20129**
Just updating the "Current State" section.

### CODE REVIEW

**Comment by ImperatorStorm** [comment]
Sodium-compatibility section is missing the link to the (last i checked) [required sodium fork](https://github.com/IrisShaders/sodium-fabric)

**Comment by OverlordsIII** [comment]
I don’t know if this should be added , but maybe add images of what iris can currently do with sildurs?

**Review by FoundationGames — CHANGES_REQUESTED** [review]
The image of acid shaders is undersized, only 500x281, I would suggest you increase the resolution for this image to match the others.
Also, the titles of the Sildur's shaders images are spelled "Sildurs' Shaders", when they should be spelled "Sildur's Shaders" [like on their site](https://sildurs-shaders.github.io/) (just being a bit picky)

**Comment by Pepe20129** [comment]
I'm stupid. I'll fix it.

**Comment by OverlordsIII** [comment]
Maybe add a link to the discord to the README? idk if it should be in this pr though

**Comment by OverlordsIII** [comment]
Maybe add some pics of sodium + iris?

**Comment by Pepe20129** [comment]
Well there's almost no visual difference.

**Comment by OverlordsIII** [comment]
No I meant just with F3 open to show it can work with Iris but I don't think it's needed, the pictures here are good enough.

**Comment by Pepe20129** [comment]
Yeah I mean I think that the F3 screen doesn't show sodium. But I may be wrong. Also I wouldn't put it either since you need the compatibily branch and a fork of Sodium.

**Comment by maxigator** [comment]
It does but not a lot it shows the sodiumcache under (or above) the coords

**Comment by IMS212** [comment]
Maybe have a separate README for the sodium compat branch?

**Comment by Pepe20129** [comment]
Yes. A separate README would be better. But that would be in a different pr.

**Review by coderbot16 — COMMENTED** [review]
I've added a link to the Discord in the README. At this time, given how quickly Iris is changing, I think it would be good to wait before adding any showcase images to the README. And when showcase images *are* added, I don't think I'll do them through Imgur - instead, I prefer having images directly in the repository (compressed JPEGs, of course, since PNG screenshots can get quite large).

**Pull request closed without merging**
